# Generated by Django 3.2.8 on 2021-10-15 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20211015_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
