# Generated by Django 3.2.8 on 2021-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211015_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='most_active',
            field=models.IntegerField(default=0),
        ),
    ]
