# Generated by Django 3.2.8 on 2021-10-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20211015_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='most_active',
        ),
    ]
